export const GET_MOVIES = "GET_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const MOVIES_LOADING = "MOVIES_LOADING";
// Auth
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

//MovieID
export const GET_MOVIEINFO_ID = "GET_MOVIEINFO_ID";
export const STORE_MOVIEINFO_ID = "STORE_MOVIEINFO_ID";
